[package]
name = "package_layout"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]




[build]
rustc-wrapper = "/home/philip/.cargo/bin/sccache"
